systemDictionary = {
    "MegaD Name:":          {"en": "MegaD Name:",           "de": "MegaD Name:",                "ru": "MegaD Имя:"},
    "ioBroker Web Port:":   {"en": "ioBroker Web Port:",    "de": "ioBroker Web Port:",         "ru": "ioBroker веб-порт:"},
    "Poll interval (sec):": {"en": "Poll interval (sec):",  "de": "Abfrage Intervall (sek):",   "ru": "Интервал опроса (сек):"},
    "MegaD Password:":      {"en": "MegaD Password:",       "de": "MegaD Kennword:",            "ru": "MegaD Пароль:"},
    "name":                 {"en": "Name",                  "de": "Name",                       "ru": "Имя"},
    "input":                {"en": "Input",                 "de": "Eingang",                    "ru": "Вход"},
    "switch":               {"en": "Switch",                "de": "Schalter",                   "ru": "Переключатель"},
    "offset":               {"en": "Offset",                "de": "Offset",                     "ru": "Сдвиг"},
    "factor":               {"en": "Factor",                "de": "Factor",                     "ru": "Множитель"},
    "digital":              {"en": "Digital",               "de": "Digital",                    "ru": "Цифровой"},
    "long":                 {"en": "Long press",            "de": "Long press",                 "ru": "Удержание"},
    "double":               {"en": "Double click ms",       "de": "Double click ms",            "ru": "Двойное нажатие"},
    "Ports":                {"en": "Ports",                 "de": "Ports",                      "ru": "Порты"},
    "Long press detect (ms):": {"en": "Long press detection (ms):", "de": "Langes-Drucken-Erkennung (ms):", "ru": "Интервал для длинного нажатия (мс):"},
    "MegaD-328 adapter settings": {"en": "MegaD-328 adapter settings", "de": "MegaD-328 Adaptereinstellungen", "ru": "MegaD-328 настройки"},
    "IP:":                  {"en": "MegaD IP:",             "de": "MegaD IP:",                  "ru": "IP Адрес устройства:"},
    "Double press detect (ms):": {"en": "Double press detect (ms):", "de": "Doppelclick-Interval(ms):", "ru": "Интервал двойного нажатия (мс):"},
    "Add new port":         {"en": "Add new port",          "de": "Neuer Port",                 "ru": "Добавить порт"},
    "Auto detect ports":    {"en": "Auto detect ports",     "de": "Auto-Detekt die Ports",      "ru": "Считать настройки с MegaD"},
    "Write config to device": {"en": "Write config to device", "de": "Konfiguration in das Gerät schreiben", "ru": "Записать настройки в устройство"},
    "Name":                 {"en": "Name",                  "de": "Name",                       "ru": "Имя"},
    "Room":                 {"en": "Room",                  "de": "Zimmer",                     "ru": "Комната"},
    "Role":                 {"en": "Role",                  "de": "Rolle",                      "ru": "Роль"},
    "Type":                 {"en": "Type",                  "de": "Typ",                        "ru": "Тип"},
    "Mode":                 {"en": "Mode",                  "de": "Modus",                      "ru": "Режим"},
    "NC":                   {"en": "Not configured",        "de": "nicht benutzt",              "ru": "не используется"},
    "Input":                {"en": "Input",                 "de": "Input",                      "ru": "Циф. вход"},
    "Output":               {"en": "Output",                "de": "Output",                     "ru": "Циф. выход"},
    "ADC":                  {"en": "Analog in (ADC)",       "de": "Analog in (ADC)",            "ru": "Ан. вход (ADC)"},
    "Digital Sensor":       {"en": "Digital Sensor",        "de": "Digital Sensor",             "ru": "Циф. датчик"},
    "normal opened":        {"en": "normal opened",         "de": "bei schliessen",             "ru": "при замыкании"},
    "on change":            {"en": "on change",             "de": "auf änderung",               "ru": "при изменении"},
    "normal closed":        {"en": "normal closed",         "de": "bei auf",                    "ru": "при размыкании"},
    "Action:":              {"en": "Action:",               "de": "Aktion:",                    "ru": "Сценарий:"},
    "Net:":                 {"en": "Net:",                  "de": "Net:",                       "ru": "Сетевой сценарий:"},
    "Long:":                {"en": "Long:",                 "de": "Lang-Click:",                "ru": "Долгое нажатие:"},
    "Double:":              {"en": "Double:",               "de": "Double-Click:",              "ru": "Двойное нажатие:"},
    "not monitored":        {"en": "not monitored",         "de": "nicht beobachtet",           "ru": "не наблюдать"},
    "> threshold":          {"en": "> threshold",           "de": "> Schwellwert",              "ru": "> порога"},
    "< threshold":          {"en": "< threshold",           "de": "< Schwellwert",              "ru": "< порога"},
    "<> threshold":         {"en": "<> threshold",          "de": "<> Schwellwert",             "ru": "<> порога"},
    "Offset:":              {"en": "Offset:",               "de": "Offset:",                    "ru": "Сдвиг:"},
    "Factor:":              {"en": "Factor:",               "de": "Faktor:",                    "ru": "Множитель:"},
    "DHT22":                {"en": "DHT22",                 "de": "DHT22",                      "ru": "DHT22"},
    "PWM":                  {"en": "PWM",                   "de": "PWM",                        "ru": "ШИМ"},
    "Default state:":       {"en": "Default state:",        "de": "Default Zustand:",           "ru": "По умолчанию:"},
    "off":                  {"en": "off",                   "de": "off",                        "ru": "выкл"},
    "on":                   {"en": "on",                    "de": "on",                         "ru": "вкл"},
    "Threshold:":           {"en": "Threshold:",            "de": "Schwellwert:",               "ru": "Порог:"},
    "Hysteresis:":          {"en": "Hysteresis:",           "de": "Hysterese:",                 "ru": "Гистерезис:"},
    "Smooth:":              {"en": "Smooth:",               "de": "Glatt:",                     "ru": "Плавный:"},
    "Change ip or password": {
        "en": "Change ip or password",
        "de": "IP Adresse oder Kennwort ändern",
        "ru": "Изменить IP или пароль"
    },
    "Take new settings into config:": {
        "en": "Take new settings into config:",
        "de": "Neue Einstellungen übernehmen:",
        "ru": "Перенять новые настройки:"
    },
    "Old IP:":             {"en": "Old IP:",               "de": "Alte IP:",                   "ru": "Старый IP:"},
    "Old password:":       {"en": "Old password:",         "de": "Altes Kennwort:",            "ru": "Старый пароль:"},
    "New IP:":             {"en": "New IP:",               "de": "Neue IP:",                   "ru": "Новый IP:"},
    "New password:":       {"en": "New password:",         "de": "Neues Kennwort:",            "ru": "Новый пароль:"},
    "Set new password or IP address": {
        "en": "Set new password or IP address",
        "de": "Set new password or IP address",
        "ru": "Изменить IP или пароль на устройстве"
    },
    "Ok":                   {"en": "Ok",                    "de": "Ok",                         "ru": "Ok"},
    "Cancel":               {"en": "Cancel",                "de": "Abrechen",                   "ru": "Отмена"},
    "Error":                {"en": "Error",                 "de": "Fehler",                     "ru": "Ошибка"},
    "Find devices":         {"en": "Find devices",          "de": "Suche Geräte",               "ru": "Искать устройства"},
    "Enable adapter first": {
        "en": "Enable adapter first",
        "de": "Aktivieren sie zuerst den adapter",
        "ru": "Сперва включите адаптер"
    },
    "Nothing found":        {"en": "Nothing found",         "de": "Nichts gefunden",            "ru": "Ничего не найдено"},
    "Information will be merged. Are you sure?": {
        "en": "Information will be merged. Are you sure?",
        "de": "Informationen werden zusammengeführt. Bist du sicher?",
        "ru": "Информация будет объединена. Вы уверены?"
    },
    "Internal Sensor":      {"en": "Internal Sensor",       "de": "Eingebauter Sensor",         "ru": "Internal Sensor"},
    "PWM:":                 {"en": "PWM:",                  "de": "PWM:",                       "ru": "PWM:"},
    "Sensor type:":         {"en": "Sensor type:",          "de": "Sensortyp:",                 "ru": "Тип сенсора:"},
    "De-bounce:":           {"en": "De-bounce:",            "de": "Entprellen:",                "ru": "Дребезг:"}
};
